### ISSUE TITLE
Invalid value processing

### ISSUE THREAD

**Issue by soukudom** [IOT-DSA/dslink-java-mqtt#4]
When the value in json body is null (e.g. {"UPS Type":"SMART-UPS 3000 RM","STATUS":"Ready","folder":null,"BatteryCapacity":"100"} ) or invalid (e.g. {"UPS Type":"SMART-UPS 3000 RM","STATUS":"Ready","folder":"null","BatteryCapacity""100"}) the link does not send anything. It just logs the following error message:

_[2018-12-04 08:24:09.552041] 2018-12-04 08:24:09.551 [MQTT Rec: xx] ERROR org.dsa.iot.mqtt.Mqtt - Lost connection to MQTT
[2018-12-04 08:24:09.552084] Connection lost (32109) - java.io.EOFException
[2018-12-04 08:24:09.552097] 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
[2018-12-04 08:24:09.552110] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2018-12-04 08:24:09.552121] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2018-12-04 08:24:09.552133] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[2018-12-04 08:24:09.552145] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[2018-12-04 08:24:09.552153] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2018-12-04 08:24:09.552159] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2018-12-04 08:24:09.552165] 	at java.lang.Thread.run(Thread.java:748)
[2018-12-04 08:24:09.552170] Caused by: java.io.EOFException
[2018-12-04 08:24:09.552176] 	at java.io.DataInputStream.readByte(DataInputStream.java:267)
[2018-12-04 08:24:09.552182] 	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
[2018-12-04 08:24:09.552189] 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:133)
[2018-12-04 08:24:09.552195] 	... 7 more
[2018-12-04 08:24:09.552201]_ 

The null value in json body is a valid item in json. For invalid json value I would expect an error message in the properties tab.

**Comment by a-hansen** [comment]
It looks like it might be this issue with the mqtt library we use:

https://github.com/eclipse/paho.mqtt.java/issues/474

Are you using mqtt qos > 0?  If so, does it go away with qos 0?

**Comment by soukudom** [comment]
In this case, it doesn't matter on the QoS value. My MQTT server is ThingsBoard and it seems that ThingsBoard for the above mentioned request returns a message that causes these errors. I would assume better exception handling in this dslink and setting error and onError properties.

**Comment by d-shapiro** [comment]
Tested with the ThingsBoard demo while running Wireshark, the issues seem to be on the Thingsboard side. Looks like the DSLink successfully sends messages to Thingsboard, regardless of what's on them. Apparently Thingsboard can't process messages with null values and will terminate the TCP connection (send a FIN packet) upon receiving one. The DSLink responds to this correctly, setting the Status field to "Disconnected" and automatically re-initiating the TCP connecction.
